### PR TITLE
added genlevel dimuon info

### PR DESCRIPTION
**Pull request by nsahoo**
Hi @pohsun and @xshi ,

I added the gen level dimuon info to the selector code. Please review and give comments..

cheers,
n.

### CODE REVIEW

**Comment by nsahoo** [comment]
To draw the efficiency ratio plot (w/ and w/o HLT requirement) as a function of dimuon pt needs to save the genlevel dimuon pt info into acceptance.root which lacks in our present fittter code.

**Comment by pohsun** [comment]
I don't understand why we need this? We have information of each muon and the dimuon can be build from muons without any resolution issue at GEN level.

**Comment by xshi** [comment]
Hi @pohsun,  could you confirm so that I can merge it. 

Thanks!

**Comment by pohsun** [comment]
@xshi This should be just the copy for the latest production, no special features added. Just merge.

**Pull request merged**
